### ISSUE TITLE
libstdc++.6.0.9.dylib 不需要的吗？

### ISSUE THREAD

**Issue by Link-Kou** [labidc/react-native-labidc-location#1]

**Comment by Link-Kou** [comment]
项目内集成的相关的依赖。

**Comment by Link-Kou** [comment]
问题已经解决谢了

**Comment by labidc** [comment]
感谢你的使用，我这段时间会抽空继续维护一下这个项目。

fannaoshaoxiang <notifications@github.com> 于2018年11月25日周日 下午6:16写道：

**Comment by labidc** [comment]
这个文件是 ios编译的时候需要的一个动态链库文件，我准备到时候把这块改造成pods 方式，这样更稳定的集成。

leo chen <labidc@gmail.com> 于2018年12月3日周一 下午2:45写道：
